### ISSUE TITLE
Custom callback type

### ISSUE THREAD

**Issue by alanpoon** [AmpMe/opensles-sys#1]
RegisterCallback requires slBufferQueueCallback as parameter. What should I do if my callback function is FnMut? 

I am trying to implement opensles in https://github.com/tomaka/cpal.

**Comment by appaquet** [comment]
This repo contains raw bindings to OpenSLES, which are not very easy to use unless you know how to use FFI code. I suggest you read read the RUST FFI documentation [here](https://doc.rust-lang.org/1.9.0/book/ffi.html) before trying to implement using this repo's bindings.

As for your question, the RegisterCallback requires a static callback function that can be called from a C context. In my project, I declare this method like this:

```rust
extern "C" fn c_render_callback(queue: opensles::bindings::SLAndroidSimpleBufferQueueItf, void_context: *mut std::os::raw::c_void) {
 ...
}
```
and then pass it like this to the RegisterCallback:
```rust
(*(*sl_player_buffer_queue)).RegisterCallback.unwrap()(sl_player_buffer_queue, Some(c_render_callback), context as *mut _ as *mut std::os::raw::c_void)
```

In order to call a FnMut, you need to put this FnMut in some kind of context that is then passed through the `context` parameter of the `RegisterCallback`, which will then be passed to `c_render_callback` by OpenSLES. This context can be a simple Rust boxed struct that you can convert to a raw pointer using [`Box::into_raw`](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.into_raw). You need to make sure you drop this context by yourself since into_raw allows you to take ownership of the memory management of this struct by converting it to a raw pointer. 

I hope this helps! Good luck!

**Comment by alanpoon** [comment]
Thanks for replying.
How to write   
SLDataLocator_IODevice loc_dev =
      {SL_DATALOCATOR_IODEVICE, SL_IODEVICE_AUDIOINPUT,
       SL_DEFAULTDEVICEID_AUDIOINPUT, NULL};
equivalent in rust? In C++, SL_DATALOCATOR_IODEVICE is a constant. But in rust, SL_DATALOCATOR_IODEVICE is type of SL_DATALOCATOR_IODEVICE_ and const.

**Comment by alanpoon** [comment]
How do you initialize sl_player_buffer_queue?

**Comment by appaquet** [comment]
There is a few C++ example online. The simplest I found is this [one](https://gist.github.com/hrydgard/3072540) and this [one](https://github.com/apportable/openal-soft/blob/master/jni/OpenAL/Alc/opensles.c). Unfortunately, using C++ from Rust can be a bit tricky in terms of syntax, but once you get over it, it's the same logic. I invite you to read Android's [introduction to opensl](https://developer.android.com/ndk/guides/audio/opensl/getting-started) and [audio latency documentation](https://developer.android.com/ndk/guides/audio/audio-latency) too. There are things you need to be careful about if you want low latency audio (ex: buffer size, sample rate, non-blocking rendering)

**Comment by alanpoon** [comment]
I use:
let mut engineObject:SLObjectItf;
unsafe{
        let result = slCreateEngine(&mut engineObject,0,.....)
}
I get the error "use of possibly uninit
ialized `engineEngine`"
