### ISSUE TITLE
quite a number of constant not added into binding.rs

### ISSUE THREAD

**Issue by alanpoon** [AmpMe/opensles-sys#2]
For instance, SL_SPEAKER_FRONT_LEFT. It is inside OpenSLES.h, but it is not inside binding.rs

**Comment by appaquet** [comment]
This repos contains the bindings generated by bindgen, and unfortunately, they it doesn't support macro defined constants. There is an [open issue](https://github.com/rust-lang-nursery/rust-bindgen/issues/316) opened in bindgen's repo.

So, in this case you have to fallback to OpenSLES headers to fine the proper value. You can find the panning constants in [OpenSLES.h](https://www.khronos.org/registry/OpenSL-ES/api/1.0/OpenSLES.h).

Since this repo was to be used inside an internal project, focus has never been to make it friendly to use. Most bindings crates that are meant to be used have 2 crates: one "sys" crate (like this one) and one Rust friendly create (usually with no unsafe exposed). Feel free to open a PR if you want to expose all those macro defined constants to this repo!
